### ISSUE TITLE
Implement search all subscriptions

### ISSUE THREAD

**Issue by shobhitvaish** [scepman/scepman-psmodule#3]
It should be possible to search all of the subscriptions through a switch. The user won't be asked to select a subscription if multiple subscriptions are found.

Ref - https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#switch-parameters

**Comment by shobhitvaish** [comment]
This is done

**Comment by shobhitvaish** [comment]
Try setting $SearchAllSubscriptions to false and see what happens with $SearchAllSubscriptions.IsPresent

**Comment by shobhitvaish** [comment]
Powershell switch ignores the bool value if provided but treats the bool value as the first parameter effectively setting the SCEPmanAppServiceName to the bool value.

**Comment by bb-froggy** [comment]
Let's try out the colon syntax, too: -SearchAllSubscriptions:$false

**Comment by shobhitvaish** [comment]
@bb-froggy You are correct. Using the colon syntax does affect the value of the switch. So, -SearchAllSubscriptions:$false sets the IsPresent to false and  -SearchAllSubscriptions:$true sets the IsPresent to true.

![image](https://user-images.githubusercontent.com/24998910/159938190-a624eb49-d48c-4cf4-afb1-403f89c58951.png)

**Comment by bb-froggy** [comment]
Good, well checked! My worry was that -SeachAllSubscriptions:$false would make IsPresent true, but some other value that should better be checked false, but luckily this is not the case. So our current code works fine even when using the explicit syntax for the flag and we can close this ticket.
